# Generated by Django 4.2.28 on 2026-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='auth_provider',
            field=models.CharField(choices=[('firebase', 'Firebase'), ('local', 'Local')], db_index=True, default='firebase', max_length=20),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['auth_provider', 'is_active'], name='users_baseu_auth_pr_1bf82b_idx'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['last_login'], name='users_baseu_last_lo_41941b_idx'),
        ),
    ]
