# Generated by Django 4.2.28 on 2026-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_auth_provider_baseuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='firebase_profile',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['synced_at'], name='users_baseu_synced__efce82_idx'),
        ),
    ]
