# Generated by Django 4.2.27 on 2026-02-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("url", models.URLField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("avatar", "Avatar"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "uploaded_at"],
                        name="storage_fil_user_id_99210d_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="storage_fil_file_ty_6ea417_idx"
                    ),
                ],
            },
        ),
    ]
