# Generated by Django 4.2.27 on 2026-02-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("pass", "Pass")], max_length=20
                    ),
                ),
                ("is_matched", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_from",
                        to="users.baseuser",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_to",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "interaction_type"],
                        name="interaction_from_us_90ce7d_idx",
                    ),
                    models.Index(
                        fields=["to_user", "interaction_type"],
                        name="interaction_to_user_9cf363_idx",
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user1",
                        to="users.baseuser",
                    ),
                ),
                (
                    "user_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user2",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["user_1", "is_active"],
                        name="interaction_user_1__998169_idx",
                    ),
                    models.Index(
                        fields=["user_2", "is_active"],
                        name="interaction_user_2__8c2503_idx",
                    ),
                ],
                "unique_together": {("user_1", "user_2")},
            },
        ),
    ]
