# Generated by Django 4.2.27 on 2026-02-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "today_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pending_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weekly_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("active_services", models.IntegerField(default=0)),
                ("total_completed_today", models.IntegerField(default=0)),
                ("total_cancelled_today", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_stats",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["worker", "date"], name="stats_opera_worker__fbf67e_idx"
                    )
                ],
                "unique_together": {("worker", "date")},
            },
        ),
    ]
