# Generated by Django 4.2.27 on 2026-02-03 18:46

import clients.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=clients.models.generate_client_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("vip", "VIP"),
                            ("corporate", "Corporate"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_requests", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("verified_account", models.BooleanField(default=False)),
                ("member_since", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("favorite_workers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="clients_cli_code_d90b4a_idx"),
                    models.Index(
                        fields=["user"], name="clients_cli_user_id_f4ed69_idx"
                    ),
                ],
            },
        ),
    ]
