# Generated by Django 4.2.27 on 2026-02-03 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_code", models.CharField(db_index=True, max_length=20)),
                (
                    "worker_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("scheduled_at", models.DateTimeField()),
                ("payment", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("confirmation_time", models.DateTimeField(blank=True, null=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_code", "status"],
                        name="work_reques_client__10c944_idx",
                    ),
                    models.Index(
                        fields=["worker_code", "status"],
                        name="work_reques_worker__403fd5_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="work_reques_status_2f052e_idx",
                    ),
                ],
            },
        ),
    ]
