# Generated by Django 4.2.27 on 2026-02-03 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "participant_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms_as_p1",
                        to="users.baseuser",
                    ),
                ),
                (
                    "participant_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms_as_p2",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("location", "Location"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("attachment_url", models.URLField(blank=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["room", "timestamp"],
                        name="chats_messa_room_id_5fcad8_idx",
                    ),
                    models.Index(
                        fields=["sender", "is_read"],
                        name="chats_messa_sender__678e0f_idx",
                    ),
                    models.Index(
                        fields=["room", "is_read"],
                        name="chats_messa_room_id_a66ce1_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["participant_1", "last_message_at"],
                name="chats_chatr_partici_6ab9af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["participant_2", "last_message_at"],
                name="chats_chatr_partici_aafcd9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("participant_1", "participant_2")},
        ),
    ]
