# Generated by Django 4.2.27 on 2026-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Audio file for voice messages (max 5MB)",
                null=True,
                upload_to="voice_messages/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("location", "Location"),
                    ("file", "File"),
                    ("audio", "Audio"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
