# Generated by Django 4.2.27 on 2026-02-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid
import workers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=workers.models.generate_worker_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("active", "Active"),
                            ("unavailable", "Unavailable"),
                            ("offline", "Offline"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("current_request_id", models.UUIDField(blank=True, null=True)),
                ("current_client_code", models.CharField(blank=True, max_length=20)),
                ("current_location", models.CharField(blank=True, max_length=255)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("heartbeat", models.BooleanField(default=False)),
                (
                    "emergency_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("warning", "Warning"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("completed_services", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("verified_account", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_profile",
                        to="users.baseuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerLocationPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pins",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["worker", "timestamp"],
                        name="workers_wor_worker__e70e49_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["code"], name="workers_wor_code_7ef0e2_idx"),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["user"], name="workers_wor_user_id_bd03c7_idx"),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["status"], name="workers_wor_status_c1a993_idx"),
        ),
    ]
